[project]
name = "plotly-app-uk-houseprices"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "dash==2.16.1",
    "dash-bootstrap-components==0.10.7",
    "dash-core-components==2.0.0",
    "dash-html-components==2.0.0",
    "flask-caching==2.1.0",
    "gunicorn==20.1.0",
    "numpy==1.24.4",
    "pandas==1.5.3",
    "plotly==5.20.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
pipeline = [
    "convertbng>=0.7.4",
    "geopandas==0.8.2",
    "nbformat>=5.10.4",
]

[tool.ruff]
line-length = 88

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = true
